include: package:flutter_lints/flutter.yaml
linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    flutter_style_todos: true
    always_declare_return_types: true
    prefer_final_locals: true
    prefer_foreach: true

